### ISSUE TITLE
TCK: SubscriberValidation should ship with default Publisher instead of forcing to impl HelperPublisher

### ISSUE THREAD

**Issue by ktoso** [reactive-streams/reactive-streams#181]
If I'm an reactive streams implementer, and my library only has Subscribers, I'd rather not be forced into implementing a proper Publisher in order to fulful `createHelperPublisher(long elements)`.

We can and should provide default implementations of VALID "simple number publishers" you can use.

**Comment by rkuhn** [comment]
Implementation has been merged, closing.
