### ISSUE TITLE
Switch to positive wording for the entire spec

### ISSUE THREAD

**Issue by viktorklang** [reactive-streams/reactive-streams#197]
NOTE: THIS IS NOT A CHANGE IN SPEC SEMANTICS

Avoid "MUST NOT" and use same wording as for other rules that require methods not to throw exceptions.

For example, currently:

~~~markdown
| <a name="3.15">15</a>     | `Subscription.cancel` MUST NOT throw an `Exception` and MUST signal `onError` to its `Subscriber` |
| <a name="3.16">16</a>     | `Subscription.request` MUST NOT throw an `Exception` and MUST signal `onError` to its `Subscriber` |
~~~

should be

~~~markdown
+| <a name="3.15">15</a>     | `Subscription.cancel` MUST return normally. The only legal way to signal failure to a `Subscriber` is via the `onError` method |
+| <a name="3.16">16</a>     | `Subscription.request` MUST return normally. The only legal way to signal failure to a `Subscriber` is via the `onError` method |
~~~

**Comment by viktorklang** [comment]
@reactive-streams/contributors Thoughts? I think we should make this improvement ASAP (thanks @DougLea for the suggestion)

**Comment by drewhk** [comment]
Actually I feel that the negative statement is better, the problem is the second part of that sentence.

**Comment by viktorklang** [comment]
@drewhk You mean the second part of the existing sentence? I agree that it is problematic. No matter what I think we ought to have the same wording for all things that have the same semantics.

**Comment by drewhk** [comment]
Clarifying: I like "MUST NOT throw an `Exception" better than "MUST return normally", in this case I feel that the negative version is crystal clear.

**Comment by viktorklang** [comment]
@drewhk Well, yes and no, is it allowed to throw a `Throwable`?
