### ISSUE TITLE
Remove gradle-wrapper.jar

### ISSUE THREAD

**Issue by ktoso** [reactive-streams/reactive-streams#201]
[reactive-streams/gradle/wrapper/gradle-wrapper.jar](https://github.com/reactive-streams/reactive-streams/blob/master/gradle/wrapper/gradle-wrapper.jar) doesn't seem to me like it she committed, right?
It's that jar that the ./gradlew script downloads when you run it and don't have gradle as I understand it?

Or is this supposed to be committed? I'd value your insight @alkemist on this one. Thanks!

**Comment by alkemist** [comment]
It needs to be there. It bootstraps the downloading of gradle if needed, and hands off to Gradle when it's installed.

**Comment by ktoso** [comment]
Okey, sorry about that then, I had mis-remembered how `./gradlew` works. Closing as invalid.
