### ISSUE TITLE
github fails to render tables in readme.md spec

### ISSUE THREAD

**Issue by ktoso** [reactive-streams/reactive-streams#206]
Just noticed that github stopped properly rendering the table layout we used for the spec:

![reactive-streams_reactive-streams](https://cloud.githubusercontent.com/assets/120979/5955428/fb67238a-a7a2-11e4-8c07-e9311347052a.png)

Not sure since when exactly. It seems though like github changed something in their rendering, we didn't touch that layout for a loong time.

**Comment by ktoso** [comment]
Just confirmed it's only broken on master. On tagged versions it's fine: https://github.com/reactive-streams/reactive-streams/tree/v1.0.0.RC1 

So it may be us and not github who broke this rendering.

**Comment by viktorklang** [comment]
Could you do a quick `blame`? (I'm at 38000 feet in the air and the WiFi isn't fantastic)

**Comment by ktoso** [comment]
Post mortem and fix in PR https://github.com/reactive-streams/reactive-streams/issues/208 ;-)
