### ISSUE TITLE
1.12 is a duplicate of 1.9

### ISSUE THREAD

**Issue by viktorklang** [reactive-streams/reactive-streams#210]
"1.9	Calling Publisher.subscribe MUST return normally except when the provided Subscriber is null in which case it MUST throw a java.lang.NullPointerException to the caller, for all other situations the only legal way to signal failure (or reject a Subscriber) is via the onError method."

"1.12	A Publisher MAY reject calls to its subscribe method if it is unable or unwilling to serve them [1]. If rejecting it MUST do this by calling onError on the Subscriber passed to Publisher.subscribe instead of calling onSubscribe."

We can, without impacting the semantics of the spec, remove rule 12 and rename 1.13 to 1.12.

**Comment by viktorklang** [comment]
@reactive-streams/contributors This doesn't change the semantics of the spec, but reduces its complexity by removing a redundant rule. If you object to this proposed change, please comment on this Issue before the 13th of February. Thank you!

**Comment by benjchristensen** [comment]
Works for me.
