### ISSUE TITLE
reactive-streams-examples must also be published on release

### ISSUE THREAD

**Issue by viktorklang** [reactive-streams/reactive-streams#217]
Since reactive-streams-tck depends on it: http://repo1.maven.org/maven2/org/reactivestreams/reactive-streams-tck/1.0.0.RC2/reactive-streams-tck-1.0.0.RC2.pom

[info] Updating {file:/Users/viktorklang/Documents/workspace/akka/}akka-stream-tck-experimental...
[warn] 	module not found: org.reactivestreams#reactive-streams-examples;1.0.0.RC2
[warn] ==== local: tried
[warn]   /Users/viktorklang/.ivy2/local/org.reactivestreams/reactive-streams-examples/1.0.0.RC2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/reactivestreams/reactive-streams-examples/1.0.0.RC2/reactive-streams-examples-1.0.0.RC2.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.reactivestreams#reactive-streams-examples;1.0.0.RC2: not found

Ping @smaldini: This must be why there were issues resolving the new version?

**Comment by viktorklang** [comment]
@smaldini Would you be able to take https://github.com/reactive-streams/reactive-streams/pull/218 and publish 'reactive-streams-examples' for version 1.0.0.RC2? Let me know if you are unable or need any assistance :)

**Comment by viktorklang** [comment]
I suspect @smaldini might be on holiday— @rkuhn you have release-credentials, could you push the RC2 artifact of the `reactive-streams-examples`?

**Comment by rkuhn** [comment]
currently in meetings, will do it later today

**Comment by viktorklang** [comment]
Thanks @rkuhn, it's much appreciated

**Comment by szeiger** [comment]
Does the TCK really need the examples? It seems to run fine without that dependency (at least for the Publisher tests)

**Comment by viktorklang** [comment]
@szeiger Yes, the TCK needs the examples (which also happens to be a great way to dogfood the examples)
